(function(){
  const saved = localStorage.getItem('theme') || 'dark';
  if (saved === 'light') document.documentElement.classList.add('light');
  document.addEventListener('click', (e)=>{
    const t = e.target.closest('#themeToggle'); if(!t) return;
    document.documentElement.classList.toggle('light');
    localStorage.setItem('theme', document.documentElement.classList.contains('light') ? 'light':'dark');
  });
})();
const content=document.getElementById('content'); const tabbar=document.getElementById('tabbar'); const walletbar=document.getElementById('walletbar'); const topbar=document.getElementById('topbar'); const authScreen=document.getElementById('auth'); const wbId=document.getElementById('wbId'); const wbBalance=document.getElementById('wbBalance'); const wbGems=document.getElementById('wbGems'); const userLine=document.getElementById('userLine'); let currentProfile=null;
async function loadPage(page){ const res=await fetch(`./pages/${page}.html`,{cache:'no-store'}); const html=await res.text(); content.innerHTML=html; if(page==='settings') bindSettings(); }
function bindSettings(){ const address=document.getElementById('address'); const phone=document.getElementById('phone'); const saveBtn=document.getElementById('saveEditable'); if(!saveBtn) return; saveBtn.addEventListener('click', async ()=>{ try{ await db.collection('users').doc(auth.currentUser.uid).update({ address: address.value.trim(), phone: phone.value.trim(), updatedAt: firebase.firestore.FieldValue.serverTimestamp() }); currentProfile.address=address.value.trim(); currentProfile.phone=phone.value.trim(); updateHeader(currentProfile); alert('Yangilandi'); }catch(e){ alert('Saqlashda xatolik: '+e.message); } }); }
function updateWallet(p){ wbId.textContent=p.numericId??'—'; wbBalance.textContent=(p.balance??0).toLocaleString('uz-UZ'); wbGems.textContent=(p.gems??0).toLocaleString('uz-UZ'); }
function updateHeader(p){ const name=[p.firstName,p.lastName].filter(Boolean).join(' '); userLine.innerHTML=`Salom, <b>${name||'Foydalanuvchi'}</b>`; updateWallet(p); }
async function allocateNumericIdClient(){ const metaRef=db.collection('meta').doc('counters'); let newId=null; await db.runTransaction(async (tx)=>{ const snap=await tx.get(metaRef); const last=snap.exists && typeof snap.data().lastUserNumericId==='number'? snap.data().lastUserNumericId:1000000; newId=last+1; tx.set(metaRef,{lastUserNumericId:newId},{merge:true}); }); return newId; }
function hasAllRequired(d){ if(!d) return false; return ['firstName','lastName','middleName','dob','address','phone','numericId','balance','gems'].every(k=>d[k]!==undefined && d[k]!==null && d[k]!=='' ); }
document.getElementById('btnGoogle')?.addEventListener('click', async ()=>{ try{ const provider=new firebase.auth.GoogleAuthProvider(); await auth.signInWithPopup(provider);}catch(e){alert(e.message);} });
document.getElementById('btnEmailSignIn')?.addEventListener('click', async ()=>{ const email=(document.getElementById('email').value||'').trim(); const pw=(document.getElementById('password').value||'').trim(); if(!email||!pw) return alert('Email va parol kiriting'); try{ await auth.signInWithEmailAndPassword(email,pw);}catch(e){alert(e.message);} });
document.getElementById('btnEmailSignUp')?.addEventListener('click', async ()=>{ const email=(document.getElementById('email').value||'').trim(); const pw=(document.getElementById('password').value||'').trim(); if(!email||pw.length<6) return alert('Email va kamida 6 belgili parol kiriting'); try{ await auth.createUserWithEmailAndPassword(email,pw);}catch(e){alert(e.message);} });
auth.onAuthStateChanged(async (user)=>{ if(!user){ authScreen.classList.remove('hidden'); [content,tabbar,walletbar,topbar].forEach(el=>el.classList.add('hidden')); return; } authScreen.classList.add('hidden'); [content,tabbar,walletbar,topbar].forEach(el=>el.classList.remove('hidden')); const userRef=db.collection('users').doc(user.uid); const snap=await userRef.get(); currentProfile=snap.exists?snap.data():null; if(!hasAllRequired(currentProfile)){ const profileModal=document.getElementById('profileModal'); const dn=(user.displayName||'').trim(); if(dn){ const parts=dn.split(' '); document.getElementById('firstName').value=parts[0]||''; document.getElementById('lastName').value=parts.slice(1).join(' ')||''; } profileModal.showModal(); document.getElementById('saveProfile').onclick=async ()=>{ const payload={ lastName: document.getElementById('lastName').value.trim(), firstName: document.getElementById('firstName').value.trim(), middleName: document.getElementById('middleName').value.trim(), dob: document.getElementById('dob').value, address: document.getElementById('pf_address').value.trim(), phone: document.getElementById('pf_phone').value.trim(), }; if(!payload.firstName||!payload.lastName||!payload.middleName||!payload.dob||!payload.address||!payload.phone) return alert('Barcha maydonlarni to‘ldiring.'); let data=currentProfile||{}; if(!data.numericId){ try{ data.numericId=await allocateNumericIdClient(); }catch(e){ alert('ID ajratishda xatolik: '+e.message); return; } } if(data.balance==null) data.balance=0; if(data.gems==null) data.gems=0; const now=firebase.firestore.FieldValue.serverTimestamp(); if(!data.createdAt) data.createdAt=now; data.updatedAt=now; const toWrite={...data,...payload,uid:user.uid}; await userRef.set(toWrite,{merge:true}); currentProfile=toWrite; profileModal.close(); updateHeader(currentProfile); loadPage('home'); }; } else { updateHeader(currentProfile); loadPage('home'); } });
tabbar.addEventListener('click',(e)=>{ const btn=e.target.closest('.tab'); if(!btn) return; document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active', t===btn)); const page=btn.dataset.page; loadPage(page); });
document.addEventListener('click',(e)=>{ const out=e.target.closest('#signOut'); if(out) auth.signOut(); });
