[[redirects]]
from = "/install"
to = "/install.html"
status = 200

[[headers]]
for = "/install.html"
  [headers.values]
  Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
for = "/pwa-install.js"
  [headers.values]
  Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
for = "/manifest.webmanifest"
  [headers.values]
  Cache-Control = "no-store, no-cache, must-revalidate"
